# Generated by Django 6.1.1 on 2026-09-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_navire', models.CharField(max_length=100)),
                ('numero_navire', models.CharField(max_length=100, unique=True)),
                ('numero_escale', models.CharField(max_length=100, unique=True)),
                ('date_arrivee', models.DateField()),
                ('date_depart', models.DateField(blank=True, null=True)),
                ('tonnage_manifest', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
