# Generated by Django 6.1.1 on 2026-09-21 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_navire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150)),
                ('type_marchandise', models.CharField(max_length=100)),
                ('quantite_initiale', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='DetailDechargement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_dechargement', models.DateField()),
                ('shift', models.CharField(max_length=50)),
                ('quantite_dechargee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nombre_equipes', models.PositiveIntegerField()),
                ('navire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details_dechargement', to='core.navire')),
                ('marchandise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details_dechargement', to='core.marchandise')),
            ],
        ),
    ]
