# Generated by Django 6.1.1 on 2026-09-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_marchandise_detaildechargement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marchandise',
            new_name='Produit',
        ),
        migrations.RenameField(
            model_name='detaildechargement',
            old_name='marchandise',
            new_name='produit',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='type_marchandise',
            new_name='type_produit',
        ),
    ]
