# Generated by Django 6.1.1 on 2026-09-21 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_marchandise_produit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detaildechargement',
            name='navire',
        ),
        migrations.RemoveField(
            model_name='detaildechargement',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='navire',
            name='tonnage_manifest',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='quantite_initiale',
        ),
        migrations.CreateModel(
            name='ProduitNavire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_initiale', models.DecimalField(decimal_places=2, max_digits=12)),
                ('navire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits_navire', to='core.navire')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='navires_produit', to='core.produit')),
            ],
        ),
        migrations.AddField(
            model_name='detaildechargement',
            name='produit_navire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='details_dechargement', to='core.produitnavire'),
        ),
    ]
