# Generated by Django 6.1.1 on 2026-09-21 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_detaildechargement_navire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaildechargement',
            name='produit_navire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details_dechargement', to='core.produitnavire'),
        ),
        migrations.AlterField(
            model_name='detaildechargement',
            name='shift',
            field=models.CharField(choices=[('MATIN', 'Matin'), ('SOIR', 'Soir'), ('NUIT', 'Nuit'), ('NUIT2', 'Nuit 2')], max_length=10),
        ),
    ]
