# Generated by Django 6.1.1 on 2026-09-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_utilisateur_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navire',
            name='date_arrivee',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='navire',
            name='numero_escale',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
