# Generated by Django 6.1.1 on 2026-09-26 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_navire_date_arrivee_alter_navire_numero_escale'),
    ]

    operations = [
        migrations.AddField(
            model_name='detaildechargement',
            name='tonnage_decharge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='produitnavire',
            name='tonnage_initial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detaildechargement',
            name='date_dechargement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FicheJournaliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_fiche', models.DateField()),
                ('navire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiches_journalieres', to='core.navire')),
            ],
        ),
        migrations.AddField(
            model_name='detaildechargement',
            name='fiche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='details_dechargement', to='core.fichejournaliere'),
        ),
        migrations.AddConstraint(
            model_name='detaildechargement',
            constraint=models.UniqueConstraint(fields=('fiche', 'produit_navire', 'shift'), name='unique_detail_fiche_produit_shift'),
        ),
        migrations.AddConstraint(
            model_name='fichejournaliere',
            constraint=models.UniqueConstraint(fields=('date_fiche', 'navire'), name='unique_fiche_navire_date'),
        ),
    ]
