# Generated by Django 6.1.1 on 2026-09-26 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_detaildechargement_tonnage_decharge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_initiale', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tonnage_initial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='core.fichejournaliere')),
                ('produit_navire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiches', to='core.produitnavire')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fiche', 'produit_navire'), name='unique_fiche_produit')],
            },
        ),
    ]
