# Generated by Django 6.1.1 on 2026-09-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ficheproduit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichejournaliere',
            name='soumise',
            field=models.BooleanField(default=False),
        ),
    ]
