# Generated by Django 6.1.1 on 2026-09-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_fichejournaliere_soumise'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitnavire',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
