# Generated by Django 6.1.1 on 2026-09-27 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_produitnavire_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheproduit',
            name='produit_navire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches', to='core.produitnavire'),
        ),
    ]
