# Generated by Django 6.1.1 on 2026-09-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_ficheproduit_produit_navire'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichejournaliere',
            name='numero_escale',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
