# Generated by Django 6.1.1 on 2026-09-28 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_fichejournaliere_numero_escale'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichejournaliere',
            name='motif_refus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichejournaliere',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée')], default='BROUILLON', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('FICHE_SOUMISE', 'Fiche soumise'), ('FICHE_VALIDEE', 'Fiche validée'), ('FICHE_REFUSEE', 'Fiche refusée')], max_length=30)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.fichejournaliere')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationFiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée')], max_length=20)),
                ('motif', models.TextField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_validations', to='core.fichejournaliere')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validations_fiches', to='core.utilisateur')),
            ],
        ),
    ]
