# Generated by Django 6.1.1 on 2026-09-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_fichejournaliere_motif_refus_fichejournaliere_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('FICHE_SOUMISE', 'Fiche soumise'), ('FICHE_VALIDEE', 'Fiche validée'), ('FICHE_REFUSEE', 'Fiche refusée'), ('MOIS_SOUMIS', 'Mois soumis')], max_length=30),
        ),
    ]
